this should pass with the new pre-commit script

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -1,12 +1,21 @@
 #!/bin/sh
-# the recommended precommit hook from ESLint https://eslint.org/docs/user-guide/integrations
-# checks all files staged for commit for lint errors
 
-for file in $(git diff --cached --name-only --cached | grep -E '\.(js|jsx)$')
-do
-  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
-  if [ $? -ne 0 ]; then
-    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
-    exit 1 # exit with failure status
-  fi
-done
+echo "Checking changed files to see if there are errors..."
+#grab all Javascript files that have changed
+changedFiles=$(git diff --staged --name-only|grep "\.js$")
+
+#run eslint against all changed files
+result=$(eslint $changedFiles)
+
+#look for the word 'error' in the results
+case $result in
+    *error*)
+        echo "$result"
+        echo
+        echo "Changes could not be committed due to errors found by ESLint. Please correct these before committing."
+        exit 1
+        ;;
+    *)
+        echo "ESLint has found no errors in the committed Javascript files."
+        ;;
+    esac
